name: "Composite Action Test"
description: "Answers any question you give it"

inputs:
  question: # id of the input
    description: 'The question you want answered'
    required: false
    default: "What is the answer to the universe?"

outputs:
  answer:
    description: "The answer to your question"
    value: ${{ steps.answer-step.outputs.answer }}

runs:
  using: composite
  steps:
    - run: echo "${{ inputs.question }} 42" >> ./answer.txt
      shell: bash
    - id: answer-step
      run: echo "answer=$(cat ./answer.txt)" >> $GITHUB_OUTPUT
      shell: bash
    # - id: upload-artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: answer
    #     path: $GITHUB_OUTPUT
