# The name of the workflow can be anything, this is what will show up in the Actions tab of the repository
name: CI

# The trigger you want for the workflow, in this case, a push to the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # The name of the job, this can be anything
  simple:
    # The type of runner you want to use, in this case, a GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }}!
  # The name of the job, this can be anything
  simple-output:
    # The type of runner you want to use, in this case, a GitHub-hosted runner
    runs-on: ubuntu-latest

    outputs:
      question: ${{ steps.question.outputs.question }}
    steps:
      - name: Capture output
        id: question
        run: echo "question=The answer to the universe?" >> $GITHUB_OUTPUT
  matrix-test:
    # The type of runner you want to use, in this case, a GitHub-hosted runner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    needs: simple-output
    steps:
      - name: echo output plus matrix stragey
        id: question
        run: echo "${{ needs.simple-output.outputs.question }}-${{ matrix.number }}"

  composite-action-test:
    runs-on: ubuntu-latest
    steps:
      - id: test-composite-action
        uses: jburns24/action-playground@master
        with:
          question: 'What should I do when I get home?'
      - run: echo Your question and answer are -- ${{ steps.test-composite-action.outputs.question-answer }}
        shell: bash
