# The name of the workflow can be anything, this is what will show up in the Actions tab of the repository
name: CI

# The trigger you want for the workflow, in this case, a push to the master branch
on:
  push:
    branches:
      - master

jobs:
  # The name of the job, this can be anything
  simple:
    # The type of runner you want to use, in this case, a GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
