name: Test Reusable workflow

on:
  push:
    branches:
      - master

jobs:
  calls-reusable-workflow:
    uses: ./.github/workflows/getting-started.yaml
    with:
      question: "What is your name?"
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The answer is ${{ needs.calls-reusable-workflow.outputs.answer }}!"
